# Generated by Django 6.0 on 2025-12-24 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notebook_usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=800, unique=True)),
                ('senha', models.CharField(max_length=800)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
