# Generated by Django 6.0 on 2025-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notebook_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
