# Generated by Django 6.0 on 2026-02-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook_usuario',
            old_name='email',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='notebook_usuario',
            name='ativo',
        ),
    ]
