# Generated by Django 6.0 on 2026-02-06 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notebook_mensagens_ia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(max_length=800)),
                ('mensagem_usuario', models.CharField(max_length=1000)),
                ('mensagem_ia', models.CharField(max_length=1000)),
            ],
        ),
    ]
