# Generated by Django 6.0 on 2026-02-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_email_notebook_usuario_nome_and_more'),
        ('chatbot_ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook_mensagens_ia',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.notebook_usuario'),
        ),
    ]
