# Generated by Django 6.0 on 2026-02-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_ia', '0002_alter_notebook_mensagens_ia_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook_mensagens_ia',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
