# Generated by Django 6.0 on 2026-02-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_ia', '0003_rename_id_usuario_notebook_mensagens_ia_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook_mensagens_ia',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notebook_mensagens_ia',
            name='id_usuario',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
