# Generated by Django 6.0 on 2026-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_ia', '0004_remove_notebook_mensagens_ia_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook_mensagens_ia',
            name='id_usuario',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='notebook_mensagens_ia',
            name='mensagem_ia',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='notebook_mensagens_ia',
            name='mensagem_usuario',
            field=models.CharField(max_length=20000),
        ),
    ]
