# Generated by Django 6.0 on 2026-02-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_ia', '0005_alter_notebook_mensagens_ia_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook_mensagens_ia',
            name='numero_mensagem',
            field=models.IntegerField(default='0'),
        ),
    ]
