# Generated by Django 6.0 on 2026-02-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notebook_mensagens_ia',
            new_name='notebook_topicos',
        ),
    ]
