# Generated by Django 6.0 on 2026-02-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_email_notebook_usuario_nome_and_more'),
        ('topicos', '0002_rename_notebook_mensagens_ia_notebook_topicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook_topicos',
            name='id_usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cadastro.notebook_usuario'),
        ),
    ]
