# Generated by Django 6.0 on 2026-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook_anotacoes',
            name='anotacao',
            field=models.CharField(max_length=20000),
        ),
    ]
