# Generated by Django 6.0 on 2026-02-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotacao', '0002_alter_notebook_anotacoes_anotacao'),
        ('topicos', '0003_notebook_topicos_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook_anotacoes',
            name='id_topicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topicos.notebook_topicos'),
        ),
    ]
